# Generated by Django 5.0.6 on 2026-06-20 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haazri", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealattendance",
            name="multiplier",
            field=models.PositiveSmallIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
